server:
  port: 8088
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  messages:
    basename: messages
#  security:
#    user:
#      password: 123456
#      name: ith13579
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework: DEBUG


